spec/Api/AttributeApiSpec.php
spec/Api/CategoryApiSpec.php
spec/Api/FamilyApiSpec.php
spec/Api/ProductApiSpec.php
spec/Client/ResourceClientSpec.php
spec/Stream/LineStreamReaderSpec.php
spec/Stream/UpsertResourceListResponseFactorySpec.php
spec/Stream/UpsertResourceListResponseSpec.php
src/Api/AttributeApi.php
src/Api/AttributeApiInterface.php
src/Api/AttributeOptionApiInterface.php
src/Api/CategoryApi.php
src/Api/CategoryApiInterface.php
src/Api/CreatableResourceInterface.php
src/Api/FamilyApi.php
src/Api/FamilyApiInterface.php
src/Api/GettableResourceInterface.php
src/Api/ProductApi.php
src/Api/ProductApiInterface.php
src/Api/UpsertableResourceInterface.php
src/Api/UpsertableResourceListInterface.php
src/Client/AkeneoPimClientBuilder.php
src/Client/ResourceClient.php
src/Client/ResourceClientInterface.php
src/HttpClient/AuthenticatedHttpClient.php
src/HttpClient/HttpClientInterface.php
src/Stream/LineStreamReader.php
src/Stream/UpsertResourceListResponse.php
src/Stream/UpsertResourceListResponseFactory.php

A snippet to see the behavior:
```
$response = $client->getCategoryApi()->upsertList([
['code' => 'new_category1'],
['code' => 'new_category2'],
['code' => 'new_category3'],
['code' => 'new_category4'],
]);
foreach ($response as $resource) {
var_dump($resource);
}
```

Api 174 : add the upsert of a list of resources

---

README.md

This PR improve the getting started.
What is missing:
- how to launch integrations tests

Improve the getting started

---

composer.json

There has been no changes since 0.2.0

Use stable version of MultipartStreamBuilder

---

spec/AkeneoPimClientSpec.php
spec/Api/AttributeGroupApiSpec.php
src/AkeneoPimClient.php
src/AkeneoPimClientBuilder.php
src/AkeneoPimClientInterface.php
src/Api/AttributeGroupApi.php
src/Api/AttributeGroupApiInterface.php
tests/v1_8/Api/AttributeGroup/GetAttributeGroupIntegration.php
tests/v1_8/Api/AttributeGroup/ListAttributeGroupIntegration.php

- Get a single attribute group 
- Get a list of attribute groups
- Get all attribute groups

API-275_API-271: Get a single attribute group and get a list/all of attribute groups

---

spec/AkeneoPimClientSpec.php
spec/Api/CurrencyApiSpec.php
src/AkeneoPimClient.php
src/AkeneoPimClientBuilder.php
src/AkeneoPimClientInterface.php
src/Api/CurrencyApi.php
src/Api/CurrencyApiInterface.php
tests/v1_8/Api/Currency/GetCurrencyApiIntegration.php
tests/v1_8/Api/Currency/ListCurrencyApiIntegration.php

- Get a single currency
- Get a list of currencies
- Get all currencies

API-272_API-277_API-279: Get a single currency and get a list/all of currencies

---

spec/Api/FamilyVariantApiSpec.php
spec/Api/ProductModelApiSpec.php
src/AkeneoPimClientBuilder.php
src/Api/FamilyVariantApi.php
src/Api/FamilyVariantApiInterface.php
src/Api/ProductModelApi.php
src/Api/ProductModelApiInterface.php
tests/v2_0/Api/FamilyVariant/ListFamilyVariantApiIntegration.php
tests/v2_0/Api/ProductModel/ListProductModelApiIntegration.php

DOC: https://github.com/akeneo/pim-api-docs/pull/134

API-409: Add list of entities

---

spec/Api/FamilyVariantApiSpec.php
spec/Api/ProductModelApiSpec.php
src/Api/FamilyVariantApi.php
src/Api/FamilyVariantApiInterface.php
src/Api/ProductModelApi.php
src/Api/ProductModelApiInterface.php
tests/v2_0/Api/FamilyVariant/UpsertFamilyVariantApiIntegration.php
tests/v2_0/Api/FamilyVariant/UpsertListOfFamilyVariantsApiIntegration.php
tests/v2_0/Api/ProductModel/UpsertListOfProductModelApiIntegration.php
tests/v2_0/Api/ProductModel/UpsertProductModelApiIntegration.php

DOC: https://github.com/akeneo/pim-api-docs/pull/136

API-412: Add Upsert product models & family variants in PHP client

---

composer.json

Add alias on branches in composer.json

---

.ci/Jenkinsfile

Reverts akeneo/api-php-client#117

Revert "CLOUD-483: Use google container builder to build docker image"

---

.travis.yml
CHANGELOG.md
README.md
composer.json
composer.lock
phpunit.xml.dist
tests/Api/ApiTestCase.php
tests/Api/CreateProductTest.php
tests/Api/GetProductTest.php
tests/Api/UpsertListProductTest.php

- Pull-up 4.0 into master
- Fix tests for phpunit 8

Merge 4.0 into master

---

.circleci/config.yml

Following #205 
Adding CI check for master after merging a branch into it

CI: Run master after merge

---

spec/Client/HttpExceptionHandlerSpec.php
src/Client/HttpExceptionHandler.php
src/Exception/MethodNotAllowedHttpException.php
src/Exception/NotAcceptableHttpException.php
src/Exception/TooManyRequestsHttpException.php
src/Exception/UnsupportedMediaTypeHttpException.php
tests/Exception/TooManyRequestsHttpExceptionTest.php

Related documentation https://github.com/akeneo/pim-api-docs/pull/553

Api 1690 error handling

---

src/Pagination/ResourceCursor.php
src/Routing/UriGenerator.php

https://github.com/akeneo/api-php-client/issues/203

Issue-203: PHP 8.1 deprecations

---

src/Search/Operator.php

https://github.com/akeneo/api-php-client/issues/199

Add missing filters

---

src/Client/AuthenticatedHttpClient.php

API-1734: Throw proper exception when automatically refreshing token fails

---

src/Api/ProductMediaFileApi.php
src/Pagination/ResourceCursor.php

https://akeneo.atlassian.net/browse/API-1798
Fixes #228

fix(API-1798): Suppress mixed return type deprecated notices

---

composer.lock

https://akeneo.atlassian.net/browse/API-1801
Closes #227

chore(API-1801): composer update

---

README.md
spec/Client/HttpClientSpec.php
src/AkeneoPimClientBuilder.php
src/Client/HttpClient.php
src/Client/Options.php
tests/Client/OptionsTest.php

https://akeneo.atlassian.net/browse/API-1853

API-1853: Add capability to change user-agent header

---

composer.json
composer.lock

https://akeneo.atlassian.net/browse/API-1875
Fixes #242

API-1875: Add symfony/options-resolver as dependency

---

src/AkeneoPimClient.php
src/AkeneoPimClientInterface.php
src/Api/AssetApi.php
src/Api/AssetApiInterface.php
src/Api/AssetCategoryApi.php
src/Api/AssetCategoryApiInterface.php
src/Api/AssetReferenceFileApi.php
src/Api/AssetReferenceFileApiInterface.php
src/Api/AssetTagApi.php
src/Api/AssetTagApiInterface.php
src/Api/AssetVariationFileApi.php
src/Api/AssetVariationFileApiInterface.php

https://akeneo.atlassian.net/browse/API-1885

API-1885: Deprecate unused routes

---

spec/AkeneoPimClientSpec.php
spec/Api/CategoryMediaFileApiSpec.php
src/AkeneoPimClient.php
src/AkeneoPimClientBuilder.php
src/AkeneoPimClientInterface.php
src/Api/CategoryMediaFileApi.php
tests/Api/DownloadCategoryMediaFileTest.php

GRF-862 : Add api/rest/v1/category-media-files/%s/download route to the client

---

spec/AkeneoPimClientSpec.php
spec/Api/SystemInformationApiSpec.php
src/AkeneoPimClient.php
src/AkeneoPimClientBuilder.php
src/AkeneoPimClientInterface.php
src/Api/SystemInformationApi.php
src/Api/SystemInformationApiInterface.php

https://github.com/akeneo/api-php-client/pull/279

[Contribution] - Implement system information API
