- .gitignore
- .php_cs.php
- Jenkinsfile
- composer.json
First version of the Jenkinsfile. This allows us to run a CI on Jenkins for:
- `php-cs-fixer`: Runs with Guzzle 6 and PHP 7.1
- `phpspec`: Runs with Guzzle 6 and PHP 5.6, PHP 7.0 and PHP 7.1
Integration tests will come later, in a dedicated PR, but Jenkinsfile is already ready for it. They will run with:
- Guzzle 5 and Guzzle 6
- PHP 5.6, PHP 7.0 and PHP 7.1
> API-175: Add the CI Jenkinsfile

- spec/Search/SearchBuilderSpec.php
- src/Search/Operator.php
- src/Search/SearchBuilder.php
The namespace and class name have to be discussed. I'm not satisfied with those, but have difficulties to find better.
I've used a optional parameter `$options` to handle the scope and the locales. It's at least not perfect, but this allows to manage specifics case like `locale` which can be plural for filter on completeness, and for potentials future cases.
It's seems to be the best compromise between user  experience and less coupling with the API
Exemple of usage : 
```
$search = new \Akeneo\Pim\Search\SearchBuilder();
$search
->addFilter('family' , 'IN', ['tshirts'])
->addFilter('completeness' , '>', 50, ['scope' => 'ecommerce'])
->addFilter('light_metering' , '=', 'test1', ['locale' => 'en_US'])
;
$response = $api->listPerPage(10, false, ['search' => $search->toArray()]);
```
> API-147: Helper search resources

- .gitignore
- composer.json
- etc/parameters.yml.dist
- phpunit.xml.dist
- tests/Api/ApiTestCase.php
- tests/CredentialGeneratorInterface.php
- tests/DatabaseInstallerInterface.php
- tests/LocalCredentialGenerator.php
- tests/LocalDatabaseInstaller.php
For each test we need to reset the data fixtures, and we need to generate credentials (i.e. clientId and secret). This is done by executing commands console in the PIM.
I add a function to assert that a resource content is the same that another one, because it can not be done natively with PHPUnit. But don't look too much closer this function because I'm going to refactor it.
> Initialize integration tests

- Jenkinsfile
- etc/parameters.yml.dist
- src/Client/ResourceClient.php
- tests/Api/ApiTestCase.php
- tests/CredentialGeneratorInterface.php
- tests/DatabaseInstallerInterface.php
- tests/DockerCredentialGenerator.php
- tests/DockerDatabaseInstaller.php
PR approved: https://github.com/akeneo/php-api-client/pull/38 (CI bug => have to create a new PR)
**The goal of this PR is to run integration tests on the CI for the PHP client of the API.**
**Important note**: the second commit with tests is just to test my PR and will be deleted before merging my PR.
Testing the API with integration tests implies to reset the database between each test.
This is not an easy task, because the PIM is in a docker and the client in another one.
The two tasks our PHPUnit should do are:
- reset the database
- generate the new client_id/secret to test the API
To be able to perform that, there is two possible configurations:
- one for local, performing `pim:installer:db` and `pim:oauth-server:create-client` directly in local
- one for docker, performing these …
> Run integration tests on the CI for the PHP client of the API

- src/Client/AkeneoPimClientBuilder.php
The discovery methods are called in internal getters instead of doing that in the constructor because they throw an exception if they find nothing. Yet, it can be the case if the user want to set a specific one.
> API-265: rework optional parameters of the client builder

- spec/Exception/HttpExceptionSpec.php
- spec/Exception/UnprocessableEntityHttpExceptionSpec.php
- spec/HttpClient/HttpClientSpec.php
- spec/HttpClient/HttpExceptionHandlerSpec.php
- src/Exception/HttpException.php
- src/Exception/UnprocessableEntityHttpException.php
- src/HttpClient/HttpExceptionHandler.php
Simplifcation de nos HTTP exception. Le code HTTP est directement celui de l'exception. Le message de l'exception est le message contenu dans le json de la réponse s'il existe, et le "reason phrase" sinon.
> API-264: simplify HTTP exception

- spec/Client/ResourceClientSpec.php
- src/Api/UpsertableResourceListInterface.php
- src/Client/AkeneoPimClientBuilder.php
- src/Client/ResourceClient.php
- src/Client/ResourceClientInterface.php
- tests/Api/ApiTestCase.php
- tests/Api/Category/UpsertListCategoryIntegration.php
I have added an integration test only for one entity for the moment (Category). I will add another for Product but that's all. The goal is to test that the "upsert list" works with a stream as parameter, not that the server API response well (it's done in tests with arrays). So to repeat this test for every entity would be too much.
> API-266: rework upsert resource list

- .ci/Jenkinsfile
- .ci/akeneo.conf
- .ci/k8s/pim_17_ce.dev.yaml
- .ci/k8s/pim_17_ce.yaml
- .ci/k8s/pim_20_ce.dev.yaml
- .ci/k8s/pim_20_ce.yaml
Bellow, full passing test matrix :
https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fapi-php-client/detail/PR-75/87/pipeline
During development, if you want to test your pubsub queue messages, you can create a full pod with one of the two Kubernetes pod templates available :
- `cd .ci/k8s` folder
- Uncomment php-api-client image in desired *.dev.yaml template
Image has to be build before. Because Jenkinsfile cleanup GCR images, you can launch it and abord after build stages (Don't forget to clean GCR images if you are allowed to or ask to an admin).
- Run `kubectl apply -f pim_20_ce.dev.yaml`
- Run `kubectl -n jenkins-dev exec -it test-php-api-client-pim20 -c <container> -- sh` to get into the container.
> Added Jenkinsfile for CI v2

- .ci/Jenkinsfile
- Jenkinsfile
- src/AkeneoPimClientBuilder.php
- tests/Common/Api/ApiTestCase.php
This PR extracts the setup of the client in the ClientBuilder, to allow a minimum override in the EE client => https://github.com/akeneo/api-php-client-ee/pull/2.
It also extracts some configuration of the ApiTestCase, to allow an easy setup of the tests in EE too.
Finally, the CI now build against Akeneo 2.0 and not the master branch.
This PR will need https://github.com/akeneo/catalogs/pull/65 and https://github.com/akeneo/pim-community-dev/pull/7119 to be merged first.
> API-417: extract setup of entities

- .gitignore
- docker-compose.yml.dist
This will ease using Docker on a local machine, and allow to reproduce the same behavior than on the CI.
`.gitignore` was also alphabetically reordered, with folder first, and hidden files last.
>  Add a compose file template 

- tests/Common/Api/ApiTestCase.php
- tests/Common/Api/Product/AbstractProductApiTestCase.php
- tests/ValuesSanitizer.php
This PR extract the product sanitation into a dedicated class, so it can be used for published products and product draft in the EE client without code duplication.
It also removes the constructor from the `ApiTestCase`, putting the initialization of some variables into the `setup` method.
~Needs https://github.com/akeneo/api-php-client/pull/89 to be merged first.~ Done
> API-421: Add a "ValueSanitizer"

- .ci/Jenkinsfile
- .gitignore
- Jenkinsfile
- tests/Common/Api/ApiTestCase.php
- tests/Common/Api/Attribute/ListAttributeIntegration.php
- tests/Common/Api/AttributeOption/ListAttributeOptionIntegration.php
- tests/Common/Api/Category/ListCategoryIntegration.php
- tests/Common/Api/Channel/ListChannelApiIntegration.php
- tests/Common/Api/Locale/ListLocaleApiIntegration.php
- tests/Common/Api/ProductMediaFile/CreateProductMediaFileApiIntegration.php
- tests/Common/Api/ProductMediaFile/GetProductMediaFileApiIntegration.php
- tests/Common/Api/ProductMediaFile/ListProductMediaFileApiIntegration.php
- tests/etc/parameters.yml.dist
- tests/v1_7/Api/Family/ListFamilyApiIntegration.php
- tests/v1_7/Api/Product/ListProductApiIntegration.php
- tests/v2_0/Api/AssociationType/ListAssociationTypeApiIntegration.php
- tests/v2_0/Api/AttributeGroup/ListAttributeGroupIntegration.php
- tests/v2_0/Api/Currency/ListCurrencyApiIntegration.php
- tests/v2_0/Api/Family/ListFamilyApiIntegration.php
- tests/v2_0/Api/FamilyVariant/ListFamilyVariantApiIntegration.php
- tests/v2_0/Api/MeasureFamily/ListMeasureFamilyIntegration.php
- tests/v2_0/Api/Product/ListProductApiIntegration.php
- tests/v2_0/Api/ProductModel/ListProductModelApiIntegration.php
This PR:
- removes two useless parameters: `pim.username` and `pim.password`, as in the EE client, we need to incarnate different users, sometime in the same scenario,
- moves the `etc/parameters.yml` in `tests` folder, as this configuration file is only used for tests,
- put all parameters under the prefix `pim` (no more `api`).
>  Refactorize parameters in tests 

- spec/Api/ProductMediaFileApiSpec.php
- src/AkeneoPimClientBuilder.php
- src/Api/ProductMediaFileApi.php
- src/Exception/UnreadableFileException.php
- src/FileSystem/FileSystemInterface.php
- src/FileSystem/LocalFileSystem.php
- tests/Common/Api/ProductMediaFile/CreateProductMediaFileApiIntegration.php
The goal is to avoid to execute `fopen` and handle errors directly in API services.
> API-487: Isolate files manipulation in a dedicated service

- .ci/Jenkinsfile
- phpunit.xml.dist
- spec/Api/AttributeOptionApiSpec.php
- src/Api/AttributeOptionApi.php
- src/Api/AttributeOptionApiInterface.php
- tests/v2_1/Api/AttributeOption/UpsertListAttributeOptionIntegration.php
I added a PhpUnit test suite for 2.1 PIM that includes the 2.0 tests. It's not ideal but we have to think to a better way to organize integration tests per PIM version, and it will be done in another PR
> API-562: upsert a list of attribute options

- .ci/Jenkinsfile
cf https://github.com/akeneo/pim-community-dev/pull/7572
> CLOUD-483: Use google container builder to build docker image

- CHANGELOG-1.0.md
- spec/Client/HttpExceptionHandlerSpec.php
- src/Client/HttpExceptionHandler.php
- src/Exception/RedirectionHttpException.php
> API-592: Handle error when the response is a redirection

- spec/Api/AssociationTypeApiSpec.php
- spec/Api/AttributeApiSpec.php
- spec/Api/AttributeGroupApiSpec.php
- spec/Api/AttributeOptionApiSpec.php
- spec/Api/CategoryApiSpec.php
- spec/Api/ChannelApiSpec.php
- spec/Api/FamilyApiSpec.php
- spec/Api/FamilyVariantApiSpec.php
- spec/Api/ProductApiSpec.php
- spec/Api/ProductModelApiSpec.php
- spec/Client/ResourceClientSpec.php
- src/Api/AssociationTypeApi.php
- src/Api/AttributeApi.php
- src/Api/AttributeGroupApi.php
- src/Api/AttributeOptionApi.php
- src/Api/CategoryApi.php
- src/Api/ChannelApi.php
- src/Api/FamilyApi.php
- src/Api/FamilyVariantApi.php
- src/Api/ProductApi.php
- src/Api/ProductModelApi.php
- src/Client/ResourceClient.php
- src/Client/ResourceClientInterface.php
With the end-points of the reference entities, we changed the way of patching resources. The requests bodies are a single JSON instead of bodies containing one JSON per line. Same for the responses.
So I added a method in the resource client to be able to patch several resources using only one JSON for the request and the response.
I renamed the method `upsertResourceList` to avoid any confusion.
> Refactor upsert list

- .travis.yml
- README.md
For PHP 7.1 composer tries to require php-http/guzzle6-adapter at version 2.0 and fails to resolve the dependencies.
As php-http/guzzle6-adapter 2.0 is not compatible with PHP 5.6 and 7.0, I changed the composer install command in Travis to force to require the 1.1 version
> Use the right version of guzzle for the CI with PHP 7.1

- CHANGELOG.md
- composer.json
- composer.lock
- spec/Client/HttpClientSpec.php
- spec/Client/ResourceClientSpec.php
- spec/Stream/MultipartStreamBuilderFactorySpec.php
- src/AkeneoPimClientBuilder.php
- src/Client/HttpClient.php
- src/MultipartStream/MultipartStreamBuilder.php
- src/Stream/MultipartStreamBuilderFactory.php
- tests/Api/CreateProductTest.php
- tests/Api/UpsertListProductTest.php
HttpPlug has been replaced by PSR-17 and PSR-18 for the interoperability.
https://github.com/php-http/httplug
```
New client implementations and consumers should use the PSR-18 interfaces directly. In the long term, we expect PSR-18 to completely replace the need for HTTPlug.
```
By doing it, we will offer a better interoperability for the future.
I wanted to do it for the 4.0, but I had some problems preventing me to achieve it.
> Update the dependencies to use PSR instead of HttpPlug

- .travis.yml
- composer.json
- phpunit.xml.dist
- tests/Api/ApiTestCase.php
- Upgrade the PHPUnit version to support the `php-7.2+` version.
- Add the `php-7.3` version because this version is stable.
- Using the PHPUnit namespace to support the latest PHP version.
> Test enhancement

- README.md
I feel like old CI statuses aren't relevant but the column will be useful when next PIM version is released
> API-1680 - Update compatibility matrix

- Makefile
- composer.json
- composer.lock
- src/AkeneoPimClientBuilder.php
When building a client with `AkeneoPimClientBuilder::buildAuthenticatedByPassword`, the returned client has no access nor refresh tokens. Both corresponding getters will simply return `null`.
For the token to be set, one have to perform at least one API call, so the lower level `AuthenticatedHttpClient::sendRequest()` method tries to get the access token and authenticate if there is none.
From an integrator POV, this is confusing, as one would expect to get the tokens right away to store them for future usage.
This PR proposes to call the authentication API when building a client with username and password. This way, the returned client already contains an access token and a refresh token.
> Directly authenticate when building with password

- README.md
Version 9.1 in Matrix compatibility is outdated, news versions are also compatible with Akeneo v6.
> Update Matrix compatibility

- composer.json
Allow symfony 7.0 version of symfony/options-resolver and 2.0 from psr/http-message-implementation in composer
> Composer allow more versions of symfony/options-resolver and psr/http-message-implementation
